name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 5

    strategy:
      matrix:
        device: ['longan-nano', 'longan-nano-lite']

    steps:
      - uses: actions/checkout@v3

      - name: Install RISC-V build dependencies
        run: sudo apt-get install build-essential binutils-riscv64-unknown-elf gcc-riscv64-unknown-elf

      - name: Build the FiveForths firmware binary for ${{matrix.device}}
        run: make ${{matrix.device}}

      - name: Obtain SHA256 hash of the firmware ${{matrix.device}}.bin
        run: sha256sum fiveforths.bin > fiveforths.bin.sha256

      - uses: actions/upload-artifact@v3
        with:
          name: fiveforths-firmware-${{matrix.device}}
          path: fiveforths.bin*
